name: Deploy to One.com

on:
  push:
    branches:
        - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: GitHub Deploy to One.com
      uses: rostimelk/one.com-deployer@master
      env:
          ONE_DOMAIN_NAME: skrybl.net
          ONE_SSH_KEY_PUBLIC: ${{ secrets.PUBLIC }}
          ONE_SSH_KEY_PRIVATE: ${{ secrets.PRIVATE }}
          TPO_SRC_PATH: ""
          TPO_PATH: ""
